### ISSUE TITLE
Revisar sección de cálculos

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/espaciales-tidy-tutorial#8]

**Comment by paocorrales** [comment]
Deberiamos discutir que hay muchas herramientas estadísticas aplicadas especificamente a cosas geo. Ademas hay muchas herramientas especificas de cada disiplina. La sección EOF necesita un poco mas de cuerpo, tal vez linkear a wikipedia u otra fuente que profundice sobre la estadística.  
La de regresiones está casi vacía. 
Para el taller contaria sobre EOF y mostraría el resultado haciendo énfasis en el significado físico pero no en el código como motivación para ver regresiones y ahí si trabajar con código.

**Comment by eliocamp** [comment]
Ahí le di una pasada. https://eliocamp.github.io/espaciales-tidy-tutorial/04_calculos.html

**Comment by paocorrales** [comment]
El mapa de la ultima figura no se ve, se adivina sudamerica pero es pedir mucho. 

Tal vez definiría mejor lo que es una regresión, que valores puede tomar y que significan. Para alguien que no la tiene tan clara

**Comment by eliocamp** [comment]
> El mapa de la ultima figura no se ve, se adivina sudamerica pero es pedir mucho.

Era una versión vieja. Ahora está bien.

**Comment by eliocamp** [comment]
Ahí agregé algo.
